### ISSUE TITLE
Swift 3 compatibiltiy

### ISSUE THREAD

**Issue by mandeepUcreate** [samuelbeek/SwiftCountryPicker#1]
Please make it compatible to swift 3.I am facing issues while compile in swift 3.

**Comment by daver234** [comment]
Me too.  Just tried it.  Line 84 of CountryPicker.swift:  type NSFastEnumerationsIterator.Element has not subscript members.

**Comment by samuelbeek** [comment]
You're right. I will work on an update

**Comment by henrykapostel** [comment]
I have the same issue too, are you already updated it? It is very urgently.

**Comment by samuelbeek** [comment]
Fixed in 1.0.1
